export { VioletPoolClient, validateSetpoint } from "./client.js";
export {
  CircuitBreaker,
  CircuitBreakerState,
  type CircuitBreakerOptions,
  type CircuitBreakerStats,
} from "./circuit-breaker.js";
export {
  ACTIONS,
  ACTION_ALLAUTO,
  ACTION_ALLOFF,
  ACTION_ALLON,
  ACTION_AUTO,
  ACTION_COLOR,
  ACTION_LOCK,
  ACTION_MAN,
  ACTION_OFF,
  ACTION_ON,
  ACTION_PUSH,
  ACTION_UNLOCK,
  API_ENDPOINTS,
  DOSING_CANISTER_ID,
  DOSING_CONFIG_PREFIX,
  DOSING_FUNCTIONS,
  ERROR_CODES,
  ERROR_SEVERITY,
  ERROR_SEVERITY_ALARM,
  ERROR_SEVERITY_INFO,
  ERROR_SEVERITY_REMINDER,
  ERROR_SEVERITY_WARNING,
  RS485_PUMP_MODES,
  RS485_PUMP_NAMES,
  SETPOINT_RANGES,
  SPECIFIC_READING_GROUPS,
  SYSTEM_SERVICES,
  TARGETS,
  type Action,
} from "./constants/api.js";
export {
  COVER_FUNCTIONS,
  CoverState,
  DEVICE_PARAMETERS,
  DmxSceneState,
  OnewireState,
  OutputState,
  PvSurplusState,
  RuleState,
  isOutputEmergency,
  isOutputManual,
  isOutputOn,
  type DeviceParameters,
} from "./constants/devices.js";
export {
  VioletAuthError,
  VioletCircuitBreakerOpenError,
  VioletPayloadError,
  VioletPoolError,
  VioletSetpointError,
  VioletTimeoutError,
  VioletUnsafeOperationError,
  type VioletErrorOptions,
} from "./errors.js";
export {
  parseEpochMilliseconds,
  parseEpochSeconds,
  parseHmsMilliseconds,
  parseOptionalMilliseconds,
  parseRuntimeMilliseconds,
  parseUptimeMilliseconds,
} from "./parsers.js";
export {
  RateLimiter,
  getGlobalRateLimiter,
  type RateLimiterOptions,
  type RateLimiterStats,
} from "./rate-limiter.js";
export { VioletReadings } from "./readings.js";
export { InputSanitizer, type NumericOptions } from "./sanitizer.js";
export {
  COVER_STATE_MAP,
  STATE_TRANSLATIONS,
  VioletState,
  getDeviceModeFromState,
  getDeviceStateInfo,
  getStateTranslationLanguage,
  setStateTranslationLanguage,
  type DeviceMode,
  type DeviceStateInfo,
  type StateLanguage,
} from "./state.js";
export type {
  CommandResult,
  ControllerRecord,
  DosingType,
  ErrorNotification,
  ErrorSeverity,
  FetchImplementation,
  HardwareProfile,
  JsonPrimitive,
  JsonRecord,
  JsonValue,
  LogResult,
  Rs485PumpMode,
  Rs485PumpName,
  SystemService,
  VioletPoolClientOptions,
} from "./types.js";
